MODEL:
    name: "BMN"
    tscale: 100
    dscale: 100
    feat_dim: 1024
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
    anno_file: "work/train17500.json" #标签存放路径
    feat_path: '/tcdata/i3d_feature' #测试使用路径''data/dataset/bmn/train/videofeature'

TRAIN:
    subset: "train"
    epoch: 20
    batch_size: 8
    num_threads: 8
    use_gpu: True
    num_gpus: 1
    learning_rate: 0.001
    learning_rate_decay: 0.1
    lr_decay_iter: 4200
    l2_weight_decay: 1e-4

VALID:
    subset: "validation"
    batch_size: 8
    num_threads: 8
    use_gpu: True
    num_gpus: 1

TEST:
    subset: "train"    #"validation"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.001
    snms_t1: 0.5
    snms_t2: 0.9
    output_path: "data/output/EVAL/BMN_results"
    result_path: "data/evaluate_results"

INFER:
    subset: "test"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.4
    snms_t1: 0.5
    snms_t2: 0.9
    filelist: '/media_ai/user_data/tmp_data/infer.list'
    output_path: "/media_ai/user_data/tmp_data"
    result_path: "/media_ai/user_data/tmp_data"
